workflows:
  football-coach-pro:
    name: Football Coach Pro
    description: Build Android APK for Football Coach Pro
    max_build_duration: 60
    environment:
      groups:
        - android_signing
      flutter: "3.16.0"
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - sala.assane@gmail.com
        notify:
          success: true
          failure: true